pip install --user pandas 
pip install --user numpy==1.18
pip install --user scipy==1.1.0
pip install --user scikit-learn==0.21.3
pip install --user keras==2.3.1
pip install --user tensorflow==1.14.0
pip install --user h5py==2.10.0
pip install --user opencv-python==4.2.0.32
pip install --user matplotlib
pip install --user seaborn
pip install --user sklearn